#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 13 10:14:33 2017

@author: selin
"""

import xml.etree.ElementTree as ET
from collections import defaultdict

class Writer(object):
    """Writer generates customized config file and command line parameters 
        for each instance. Choice is made upon flag generated by Distributor."""
        
    def __init__(self, data, content):
        self.data = data
        self.content = content
        
    def eval_input(self, suite):
        
        print self.content
        options = defaultdict(lambda: (None, None), 
                              {'version': (suite, None), 
                               'test': (None, suite), 
                               'versiontest': (suite[0], suite[-1])})
        return options[self.content]
        
    def get_parameters(self, suite):
        
        cl_params = self.data['CL-params']
        if suite:
            tmp = ''
            for i in range(0, len(suite)-1): # collect tests
                tmp += suite[i] + ','
            tmp += suite[-1]
            cl_params['--tests'] = tmp
            # add --tests for TestDistributor    
        cl_params['-f'] = '/home/selin/tmp/cloud-config.xml' # overwrite local config-specification
        # generate file containing individual command line arguments
        with open('cl-params.txt', 'w') as cl_file:
            for param in cl_params:
                cl_file.write(param + ' ' + cl_params[param] + ' ')
        # TODO: fix this, why is cl_params global?
        if suite:
            del cl_params['--tests']
        return cl_file
    
    def get_config(self, suite):
        
        tree = ET.parse(self.data['config'])
        root = tree.getroot()
        # adapt start and end tag in config for each instance
        root.find('.//project').attrib['dir'] = '/home/selin/tmp/project/' + root.find('.//project').attrib['dir'].split('/')[-1]
        root.find('.//project/jmh_root').attrib['dir'] = '/home/selin/tmp/project/benchmarks'
        if suite:
            root.find('.//project/versions/start').text = suite[0] # only do this if VersionDistributor or TestVersionDistributor
            root.find('.//project/versions/end').text = suite[-1]
        config = 'cloud-config.xml'
        tree.write(config, encoding='utf-8', xml_declaration=True)
        return config
    
    def generate_input(self, test_suite):
        
        versions, tests = self.eval_input(test_suite)
        config = self.get_config(versions)
        param = self.get_parameters(tests)
        return config, param
    